### ISSUE TITLE
ownMc Design

### ISSUE THREAD

**Issue by Johann-S** [Strikesoft/ownMc#11]
Maybe it would be interesting to do a design like this Bootstrap theme : http://themes.getbootstrap.com/products/application

Any thoughts @Strikesoft/core ?

**Comment by xfroelicher** [comment]
Hum... why not ! But what do we share ? Video only or all types of media ?
We can do something like netflix too : https://www.netflix.com/fr/

2015-11-26 14:04 GMT+01:00 Johann notifications@github.com:

**Comment by Johann-S** [comment]
Yes to begin video would be a good start, but yes maybe later we will support other medias
