### ISSUE TITLE
Which database

### ISSUE THREAD

**Issue by Johann-S** [Strikesoft/ownMc#12]
What kind of database do you want to use ? Relational (mysql), NoSQL (Redis, MongoDB)

I think if ownMc become a success we will have to support a lot's of DB but for the first release we have to choose one.

In my own opinion MySQL would be a good start because a lot's of people use this DB.

@Strikesoft/core

**Comment by xfroelicher** [comment]
+1 MySQL

2015-11-26 14:10 GMT+01:00 Johann notifications@github.com:

**Comment by Johann-S** [comment]
MySQL Adopted for the first release
