### ISSUE TITLE
Thinking about a UI framework

### ISSUE THREAD

**Issue by Johann-S** [Strikesoft/ownMc#7]
Which framework ?
- Bootstrap 4 ?
- Bootstrap 3 ?
- Foundation 6 ?

**Comment by Johann-S** [comment]
I think I'll chose Bootstrap 4 because it's an alpha and our project have time before the first release.

Any thoughts @Strikesoft/core ?

**Comment by xfroelicher** [comment]
+1 Bootstrap 4 !
